version: '3.8'

services:
  # RSS Main Process (Feed monitoring and job creation)
  newsrss-main:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: newsrss-rss-main
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SERVICE_NAME=RSS_MAIN
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    networks:
      - newsrss-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('RSS Main Process Health Check OK')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RSS Worker Process (Article processing and AI summarization)
  newsrss-worker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: newsrss-rss-worker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SERVICE_NAME=RSS_WORKER
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    networks:
      - newsrss-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('RSS Worker Process Health Check OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 2  # Scale workers as needed

  # AI Search Service (Independent AI news search)
  newsrss-ai-search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsrss-ai-search
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SERVICE_NAME=AI_SEARCH
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    networks:
      - newsrss-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('AI Search Service Health Check OK')"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  newsrss-network:
    driver: bridge 